### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by ssrballin** [mattbierner/MinutesToMidnight#1]
Hey I just tried using this, but it might be broken now? It goes straight to the catch block.

**Comment by mattbierner** [comment]
Thanks. I've published a fix with 0.1.0. 

There's no actual API for the doomsday clock as far as I know, so the method of extracting this data is  unreliable. Since the previous RSS method broke, I've switched to scraping the data from the thebulletin website directly. This may also break in the future when they update their website design

**Comment by ssrballin** [comment]
Makes total sense - thank you so much!
